# Generated by Django 6.0.3 on 2026-03-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_extracted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='simplified_text',
            field=models.TextField(blank=True),
        ),
    ]
