# Generated by Django 6.0.3 on 2026-03-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_document_simplified_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
