# Generated by Django 6.0.3 on 2026-03-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='simplified_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
