# Generated by Django 5.2.12 on 2026-03-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_extracted_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='simplified_text',
            new_name='summary',
        ),
        migrations.RemoveField(
            model_name='document',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='document',
            name='tamil_audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
